spring:
  profiles: dev-nossl

eureka:
  instance:
    hostname: localhost
    home-page-url: http://localhost:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:65350/eureka/        
---
spring:
  profiles: dev
  
eureka:
  instance:
    hostname: localhost
    nonSecurePortEnabled: false
    securePortEnabled: true
    secure-port: ${server.port}
    home-page-url: https://localhost:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://localhost:65350/eureka/
 
server:
  ssl:
    enabled: true
    key-store: classpath:payments.jks
    key-store-password: 123456
    key-password: 123456
    trust-store: classpath:payments.jks
    trust-store-password: 123456
    key-alias: payments
       
---
spring:
  profiles: prod
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
  instance:
    hostname: localhost