

spring:
  profiles: dev
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: coder
    password: coder
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect  
eureka:
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    secure-port: ${server.port}
    home-page-url: https://localhost:${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://localhost:65350/eureka/
    
server:
  ssl:
    enabled: true
    key-store: classpath:db.jks
    key-store-password: 123456
    key-password: 123456
    trust-store: classpath:db.jks
    trust-store-password: 123456
    key-alias: db      
---
spring:
  profiles: prod
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: coder
    password: coder
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
  instance:
    hostname: localhost